### ISSUE TITLE
sudo in Ubuntu wiki article outdated

### ISSUE THREAD

**Issue by kjdemonte** [snori74/linuxupskillchallenge#10]
Under Resources in Lesson 03, you include a link to https://help.ubuntu.com/community/RootSudo. The top of that wiki page states 

March 14, 2019 PLEASE NOTE: This wiki article is being significanly rewritten as it contains a good deal of old, dated and possibly questionable material. Using caution and consulting with others on the Ubuntu Forums or Ask Ubuntu is highly recommended!
--

Not sure if it would make sense to find another resource with more up-to-date information, or simply make a note about it in the instructions. Mostly just wanted to bring it to your attention.

**Comment by janbue** [comment]
@snori74 I will look into it and update on here.

**Comment by snori74** [comment]
Ta, pretty sure I decided it was ok despite that warning - and it's the
original doc/justification . But it does look scary...

Ubuntu was the leader in promoting sudo.

**Comment by janbue** [comment]
As far as I could find it is still the best ressource I could find, I consider this issue as closed. I might add the link to the arch wiki where there is an up to date version of everything, but it's not as in depth as the ubuntu one.
