### ISSUE TITLE
Suggestion for Day 0 - Oracle Cloud

### ISSUE THREAD

**Issue by ChrisKar96** [snori74/linuxupskillchallenge#103]
Hello! I would like to suggest Oracle Cloud always free tier as an option for day 0. 

Signing up for always free tier at Oracle Cloud, requires a credit (or debid) card but never charges anything if you only use services with the "always free" label. Always free users are eligible for 2 VM.Standard.E2.1.Micro with 2 CPU cores, 1 GB RAM and 100 GB storage each.

You can find more information about it here: https://www.oracle.com/cloud/free/

If you are interested, I can prepare a pull request for instructions for signing up, creating instances and opening the firewall, as it is preconfigured to allow only port 22 for ssh. 

Please note, I am in no way affiliated with Oracle or its Cloud service, I just use it and thought it could be a more worthwhile alternative than the services you suggest, in terms of provided features for no cost.

**Comment by snori74** [comment]
Yup, happy to receive such a PR.

Follow the same format, intro text as the others, and be careful to double
check (I'm embarrassed by the Google one, which starts off well and then
has references to EC2...)

**Comment by snori74** [comment]
Closing. If you wish, re-raise this at the Livia's fork at:

https://github.com/livialima/linuxupskillchallenge

- which is now the official live version.

Thanks, 

 - Steve
