### ISSUE TITLE
Day 19 - link rot

### ISSUE THREAD

**Issue by snori74** [snori74/linuxupskillchallenge#104]
u/CodeCage_TT98 says:

*"I didn't find the 3rd link under the RESOURSES section very helpful at all. After getting to the main page all the links to the "Part" pages all the links to those pages were broken. It appeared that they would provide a lot of additional information, but no such luck."*

**Comment by janbue** [comment]
I will look into it

**Comment by janbue** [comment]
The given link is indeed linking to many dead links, maybe we want to replace it with this link ( [https://www.howtogeek.com/465350/everything-you-ever-wanted-to-know-about-inodes-on-linux/](https://www.howtogeek.com/465350/everything-you-ever-wanted-to-know-about-inodes-on-linux/) ). I think it's explaining the concept and importance for the filesystem of inodes pretty well.

**Comment by snori74** [comment]
Done
