### ISSUE TITLE
Suggestion for Day 0 Google Cloud

### ISSUE THREAD

**Issue by wyphan** [snori74/linuxupskillchallenge#105]
The intro part about opening up the firewall seems to be outdated? The "Network" button is missing from the left menu. But there's this button (see screenshot below):

![Screenshot from 2020-11-29 16-20-21](https://user-images.githubusercontent.com/50928756/100553924-1f19d280-325f-11eb-93e9-8d568529866a.png)

Edit: nvm, found it in the home menu
![Screenshot from 2020-11-29 16-28-51](https://user-images.githubusercontent.com/50928756/100554058-42914d00-3260-11eb-9b7a-faceda3001ea.png)

**Comment by wyphan** [comment]
Now, about changing the boot disk to Ubuntu. Looks like I had to go to the Marketplace and search for "ubuntu focal" there to be able to perform this task correctly...
![Screenshot from 2020-11-29 16-55-33](https://user-images.githubusercontent.com/50928756/100554636-f0eac180-3263-11eb-9881-e3ae1626883b.png)

**Comment by snori74** [comment]
Thanks. I'll need to go through this myself at least once I think to be sure that we're giving the right information. I've also seen that people seem to get tangled up with the ssh connection later - Google tries to get you to use their own proprietary system I think. (This is why the Google "Day 0" instructions are not being posted for the moment...)

**Comment by snori74** [comment]
Closing. If you wish, re-raise this at the Livia's fork at:

https://github.com/livialima/linuxupskillchallenge

- which is now the official live version.

Thanks, 

 - Steve
