### ISSUE TITLE
Day 17 issue with updatedb

### ISSUE THREAD

**Issue by saltillokid11** [snori74/linuxupskillchallenge#106]
Where we request the user to run `sudo updatedb` we should also note that they may need to run `sudo apt install locate` to use updatedb otherwise they will get a `sudo: updatedb: command not found` output

**Comment by janbue** [comment]
Isn't locate installed the Day prior?

**Comment by snori74** [comment]
Indeed, if "locate" is not installed by default, (it may differ by distro/version) - then the best place to address that is back on Day 11

**Comment by snori74** [comment]
No action needed for now
