### ISSUE TITLE
Suggestion to add redirection , file descriptor in the tutorial.

### ISSUE THREAD

**Issue by ME-ON1** [snori74/linuxupskillchallenge#110]
Was learning about the redirection and file descriptor after completing this challenge. Found this very good article after searching ,imo 

https://catonmat.net/bash-one-liners-explained-part-three

**Comment by snori74** [comment]
Closing. If you wish, re-raise this at the Livia's fork at:

https://github.com/livialima/linuxupskillchallenge

- which is now the official live version.

Thanks, 

 - Steve
