### ISSUE TITLE
Error in Lesson 8

### ISSUE THREAD

**Issue by janbue** [snori74/linuxupskillchallenge#24]
"Apache2 web browser" is written in lesson 8 in the beginning. I think it should be "Apache2 web server". Correct me if I'm wrong. Will put in a pull request to change this and other issues I find while working through it adding backticks. Backticks are going to be a different pull request

**Comment by snori74** [comment]
Good stuff, thanks for your work on this. It's amazing to see how many
little 'glitches' remain on the notes - but super good to see them being
resolved.
