### ISSUE TITLE
Day 14, give (tested!) Instructions on how to setup login to "helper" - esp. via keys

### ISSUE THREAD

**Issue by snori74** [snori74/linuxupskillchallenge#28]

**Comment by shivan-s** [comment]
### Passwords are easy, keys are difficult
The problems come if you are using key-pair to access your server through PuTTY on Windows. To login to your remote server using your newly created user, you will need to create a new key-pair.

`sudo su - <user name>` can allow access to your newly created user. However, this requires access to your `ubuntu` user that you created initially. 

If you are using AWS EC2 instance. Logon to your AWS console. For there, you can generate a new key-pair. Save the private key to a safe location as you can only do this once.

Using PuTTYgen extract a public key from the private key and copy this.

Log back into your server using your initial `ubuntu` user.

Use `sudo su - <user name>`  to log into your new user.

`mkdir .ssh` is going going to create a new directory to hold our public key.

`chmod 700 .ssh` will see the appropriate permission.

`touch .ssh/authorized_key` will create the `authorized_key` file to hold our public key.

`chmod 600 .ssh/authorized_keys` will see the appropriate permission for this new file.

Using `cat authorized_keys`, enter the file and right-click to paste the public key. Save the file.

You may have to enter back using `vim` and add ssh-rsa to the front of the public key and also delete any linebreaks.

And Voilà, you can now access your remote server by logging on directly using you new user and the associated private key.

Resources: https://aws.amazon.com/premiumsupport/knowledge-center/new-user-accounts-linux-instance/

**Comment by snori74** [comment]
Closing. If you wish, re-raise this at the Livia's fork at:

https://github.com/livialima/linuxupskillchallenge

- which is now the official live version.

Thanks, 

 - Steve
