### ISSUE TITLE
Update order of Resources and Extensions sections each day to make them consistent

### ISSUE THREAD

**Issue by ACyphus** [snori74/linuxupskillchallenge#36]
Different days have different orders for the Resources and Extensions sections. For example:

* Day 1 - Extension then Resources - https://github.com/snori74/linuxupskillchallenge/blob/master/01.md#extension
* Day 3 - Resources then Extension - https://github.com/snori74/linuxupskillchallenge/blob/master/03.md#resources

Ideally the order of these sections would be consistent for all days (at least in my opinion 😀). I haven't been through all the days yet so I'm not sure how far reaching this is.

P.S. Thanks @snori74 for this amazing resource!

**Comment by snori74** [comment]
Thanks, I have a few days free before next month, so I'm hoping to be able to knock off a lot of the minor annoyances.

**Comment by snori74** [comment]
Tidied up as per suggestion
