### ISSUE TITLE
New Day 00 documnt on alternatives

### ISSUE THREAD

**Issue by snori74** [snori74/linuxupskillchallenge#48]
Point to Linode, Vultr etc as "often recommended by experienced users..."
Ways to get a server without a credit card:

 - Privacy.com
 - Educational (e.g.:
 - https://aws.amazon.com/education/awseducate/aws-educate-faqs/, https://edu.google.com/programs/students/benefits/?modal_active=none,
 - https://education.github.com/pack?utm_source=github+digitalocean
 - https://azure.microsoft.com/en-us/free/students/
 Add/replicate vomments on why "local" options like your own lappir, WSL, a VM or Pi are Not Good.

**Comment by snori74** [comment]
Have begun a new Day 0 document today...

**Comment by westofer** [comment]
#52

**Comment by snori74** [comment]
Document is underway
