### ISSUE TITLE
Lesson 9 - Netstat is obsolete

### ISSUE THREAD

**Issue by Shourai** [snori74/linuxupskillchallenge#5]
In lesson 9 `netstat` is used to check for open ports, however `netstat` is obsolete and should be replaced by e.g. `ss`.
See also the manual of netstat

```
This  program  is  mostly  obsolete.  
Replacement for netstat is ss.
Replacement for netstat -r is ip route.  
Replacement for netstat -i is ip -s link. 
Replacement for netstat -g is ip maddr.
```
To get pretty much the same output as netstat in the example consider using `ss -tulpen`.

Saw your post today on /r/linux, it's a great initiative!
Thank you for doing this!

There is always something new to learn, I'll be following along for the coming month ;)

**Comment by snori74** [comment]
Thanks for that, will check out and update the notes!

- Steve

**Comment by snori74** [comment]
Now done
