### ISSUE TITLE
Is this a typo?

### ISSUE THREAD

**Issue by yahyaanwar** [snori74/linuxupskillchallenge#50]
After reading the article on the second day, I feel like the word on this line should be "or" not "of".

In this file: https://github.com/snori74/linuxupskillchallenge/blob/master/02.md

"A note on switches: Generally most Linux command will accept one ~~of~~ **or** more "parameters", and one or more "switches". So, when we say ls -l /var/log the "-l" is a switch to say "long format" and the "/var/log" is the "parameter". Many commands accept a large number of switches, and these can generally be combined (so from now on, use ls -ltra, rather than ls -l -t -r -a"

**Comment by snori74** [comment]
Yup good spotting! Feel free to do a "pull request" if you know how. Once i approve that it make you officially a contributor to This Fine Project.
Otherwise I'll just do the fix, but give you credit!

**Comment by snori74** [comment]
Great stuff. Merged
