### ISSUE TITLE
Day 15 - Duplicate listing "ARM" on chips

### ISSUE THREAD

**Issue by jimmypark0** [snori74/linuxupskillchallenge#56]
Thank you for providing a great articles.

I found duplicate listing "ARM" on chip of REPOSITORIES AND VERSIONS section in Day 15.
I guess, this should have been "AMD" instead of ARM.

https://github.com/snori74/linuxupskillchallenge/blob/master/15.md#repositories-and-versions

**Comment by snori74** [comment]
Good spotting! Now fixed.
