### ISSUE TITLE
IBM Cloud Free Trail Hyper Protect Virtual Server requires Credit Card to activate

### ISSUE THREAD

**Issue by tomjuggler** [snori74/linuxupskillchallenge#57]
It's possible this is because I don't have a US based IP, but I was directed to sign up for the Pay-as-you-go plan (with $200 credit) in order to activate the Virtual Server. Not sure what services are really available with the Free Trail but it's not the one for this course.

**Comment by snori74** [comment]
Thanks for that. I'll certainly be asking those in "odd" places to check out before recommending or spending time writing up a full "Day 0" post.

No point if it only works for those who already have lots of options.

**Comment by snori74** [comment]
Closing. If you wish, re-raise this at the Livia's fork at:

https://github.com/livialima/linuxupskillchallenge

- which is now the official live version.

Thanks, 

 - Steve
