### ISSUE TITLE
Add automatic regular checks for links in Markdown files

### ISSUE THREAD

**Issue by theold190** [snori74/linuxupskillchallenge#63]
It is possible to add an automatic regular check for links in Markdown files. This way it is possible to detect broken links before users do that. It can be done using Github actions + markdown-link-check tool. Checks can be performed on push, on pull request and on schedule (supporting cron syntax).

More information in https://github.com/gaurav-nelson/github-action-markdown-link-check.

**Comment by snori74** [comment]
Closing. If you wish, re-raise this at the Livia's fork at:

https://github.com/livialima/linuxupskillchallenge

- which is now the official live version.

Thanks, 

 - Steve
