### ISSUE TITLE
Day 13: use of the 'login' switch

### ISSUE THREAD

**Issue by dwightgunning** [snori74/linuxupskillchallenge#71]
I notice that in two places, the lesson copy includes

> `sudo su fred` - to "become fred"

I am wondering if the dash after the command is actually intended to be part of the command,  e.g.

`sudo su - fred`

Use of the the 'login' switch is fairly common so I figure this may have been the intention.

**Comment by snori74** [comment]
No. However having an "inline" comment like does have the potential to confuse - so I'll edit it now. Thanks for the headsup
