### ISSUE TITLE
Typo in Day 2

### ISSUE THREAD

**Issue by robbie888** [snori74/linuxupskillchallenge#74]
Hi, 

Noticed a typo on day 2's article, in the step-by-step section, point 10 discussing hidden files. 

Quote: "and many other commands, will ignore then."
I believe the last word should be "them" not "then".

Cheers.

**Comment by snori74** [comment]
Good man! I'll get on to sorting this in an hour or two.
 -Steve

**Comment by snori74** [comment]
Done, thanks again.
