### ISSUE TITLE
Add a "Next course starts..." post

### ISSUE THREAD

**Issue by snori74** [snori74/linuxupskillchallenge#79]
This should involve getting the "next month" string working
Need to generate the date in a suitable format, e.g, "Monday, 5 October 2020"

**Comment by bernardini687** [comment]
Hi! Thanks for this wonderful course.

I'd like to give it a shot and propose something for this issue:
I don't know if you already had something in mind for this, but after some pondering around, I came up with using a github workflow to calculate the date on the ubuntu instance provided for the workflow, and then shoveling some simple markdown with the date on a `next-course-starting-date.md` file, which would then be added to the repo by the workflow.

If you'd like, you can check it out in a fork I did:
https://github.com/snori74/linuxupskillchallenge/compare/master...bernardini687:next-course-starting-date

For getting the date, I came up with:
```bash
START_DAY=`ncal -m $(($(date +%m) + 1)) -M | grep Mo | tr ' ' '\n' | grep -v ^$ | sed -n '2p'`
FORMATTED_DATE=`date -d "$(date +%Y-%m-$START_DAY) 1 month" '+%A %-d %B, %Y.'`
echo -e "# Next course starting date:\n$FORMATTED_DATE\n" > next-course-starting-date.md
```

I bet there are cleaner ways to achieve the result!
Also, maybe relying on the github workflows is not something you'd like.
This is mainly an idea, I'm more than open to discuss it and eventually try something else :)

Thanks again!

**Comment by snori74** [comment]
Cool! (Date stuff always makes my head hurt). However,  I'm now doing the posting of lessons etc. via a Python 'bot' (github.com/snori74/auto-luc), and so I plan to add some logic to that for this over the next week or so.

**Comment by bernardini687** [comment]
Makes sense!

**Comment by snori74** [comment]
Done, a while back
