### ISSUE TITLE
Day 2 - Mention `pushd` and `popd`?

### ISSUE THREAD

**Issue by VictorCMiraldo** [snori74/linuxupskillchallenge#80]
Should we mention the existence of `pushd` and `popd` when first showing navigation commands?

At least for me, using `pushd` was a game changer for getting productive in the terminal and I believe it can make
a beginner's life much easier to know about these commands early on.

I'm happy to write a paragraph or two with examples in a PR if there is interest.

**Comment by snori74** [comment]
OK, that sound fine. Do your best to explain clearly, but simply - ie no wall-of-text - and if you have a favorite tutorial link then include that down the bottom in 'resources" in the normal way too. 

Chances are that unless it's horrible I'll merge it in, and then tweak if necessary.
