### ISSUE TITLE
Day 1 - talk about ssh config file

### ISSUE THREAD

**Issue by heitorPB** [snori74/linuxupskillchallenge#87]
I think it would be very instructive to mention the `~/.ssh/config` and how to setup an alias to `ssh myserver` instead of `ssh -i path -p 666 user@host.com`.

What do you think?

**Comment by snori74** [comment]
Yes, I've just updated the notes: "A very slick connection process can be setup with the .ssh/config feature - see the "SSH client configuration" link in the EXTENSION section below." See at: https://github.com/snori74/linuxupskillchallenge/blob/master/01.md
