### ISSUE TITLE
Two additional extra resources

### ISSUE THREAD

**Issue by heitorPB** [snori74/linuxupskillchallenge#98]
I just finished the course on Reddit and it was amazing. Thank you!

I have two suggestions for extra resources to add:

- day 14: I always confuse `adduser` and `useradd`, this [ServerFault](https://serverfault.com/questions/218993/whats-the-difference-between-useradd-and-adduser) question has a nice explanation about their differences
- day 15: about package managers, ArchWiki has a [Rosetta](https://wiki.archlinux.org/index.php/Pacman/Rosetta) page, that "translates" commands from one package manager to other. It is a nice reference when dealing with different systems.

**Comment by snori74** [comment]
Great, I'll check those out and look at adding them.

**Comment by snori74** [comment]
Done!
