### ISSUE TITLE
Day 0 - Creating Your Own Server - without a credit card (Typo found)

### ISSUE THREAD

**Issue by daprw** [snori74/linuxupskillchallenge#99]
Hello! First just wanted to say thank you for putting this all together. I just happened across the subreddit the other night browsing around for Linux stuff to do and this is probably one of the more exciting things I have come across. Keep up the good work! 

I found 2 typos on the "Day 0 -Creating Your Own Server - without a credit card" page where it shows the word "Trail" instead of "Trial". I have marked the specific location below but the first one is at the H2 for "Free Trail":

https://github.com/snori74/linuxupskillchallenge/blob/master/00-Remote-server-without-Credit-Card.md#free-trail

Then, further on in that same section where the IBM Free link is listed in the bullet point, it shows "30 days trail" instead of "30 days trial". 

Cheers!

**Comment by snori74** [comment]
Thanks! Now fixed
